import sys
from nomad.metainfo import Environment
from nomad.metainfo.legacy import LegacyMetainfoEnvironment
import fploparser.metainfo.fplo
import nomad.datamodel.metainfo.common
import nomad.datamodel.metainfo.public
import nomad.datamodel.metainfo.general
import fploparser.metainfo.fplo_temporaries
import fploparser.metainfo.fplo_input_autogenerated

m_env = LegacyMetainfoEnvironment()
m_env.m_add_sub_section(Environment.packages, sys.modules['fploparser.metainfo.fplo'].m_package)  # type: ignore
m_env.m_add_sub_section(Environment.packages, sys.modules['nomad.datamodel.metainfo.common'].m_package)  # type: ignore
m_env.m_add_sub_section(Environment.packages, sys.modules['nomad.datamodel.metainfo.public'].m_package)  # type: ignore
m_env.m_add_sub_section(Environment.packages, sys.modules['nomad.datamodel.metainfo.general'].m_package)  # type: ignore
m_env.m_add_sub_section(Environment.packages, sys.modules['fploparser.metainfo.fplo_temporaries'].m_package)  # type: ignore
m_env.m_add_sub_section(Environment.packages, sys.modules['fploparser.metainfo.fplo_input_autogenerated'].m_package)  # type: ignore
